"""Circuit ID aliases and display names."""

CIRCUIT_ID_MAP: dict[str, str] = {
    "sakhir": "sakhir",
    "jeddah": "jeddah",
    "melbourne": "melbourne",
    "imola": "imola",
    "miami": "miami",
    "monaco": "monaco",
    "monte_carlo": "monaco",
    "barcelona": "barcelona",
    "montréal": "montreal",
    "montreal": "montreal",
    "silverstone": "silverstone",
    "spielberg": "spielberg",
    "le_castellet": "le_castellet",
    "budapest": "budapest",
    "spa-francorchamps": "spa",
    "spa_francorchamps": "spa",
    "spa": "spa",
    "zandvoort": "zandvoort",
    "monza": "monza",
    "marina_bay": "marina_bay",
    "singapore": "marina_bay",
    "suzuka": "suzuka",
    "lusail": "lusail",
    "austin": "austin",
    "mexico_city": "mexico_city",
    "são_paulo": "sao_paulo",
    "sao_paulo": "sao_paulo",
    "las_vegas": "las_vegas",
    "yas_island": "yas_island",
    "yas_marina": "yas_island",
    "baku": "baku",
    "shanghai": "shanghai",
    "hockenheim": "hockenheim",
    "istanbul": "istanbul",
    "mugello": "mugello",
    "nürburgring": "nurburgring",
    "nurburgring": "nurburgring",
    "portimão": "portimao",
    "portimao": "portimao",
    "sochi": "sochi",
}

CIRCUIT_NAMES: dict[str, str] = {
    "sakhir": "Bahrain Grand Prix",
    "bahrain": "Bahrain Grand Prix",
    "jeddah": "Saudi Arabian Grand Prix",
    "melbourne": "Australian Grand Prix",
    "albert_park": "Australian Grand Prix",
    "imola": "Emilia Romagna Grand Prix",
    "miami": "Miami Grand Prix",
    "monaco": "Monaco Grand Prix",
    "monte_carlo": "Monaco Grand Prix",
    "barcelona": "Spanish Grand Prix",
    "catalunya": "Spanish Grand Prix",
    "baku": "Azerbaijan Grand Prix",
    "montréal": "Canadian Grand Prix",
    "montreal": "Canadian Grand Prix",
    "silverstone": "British Grand Prix",
    "spielberg": "Austrian Grand Prix",
    "red_bull_ring": "Austrian Grand Prix",
    "le_castellet": "French Grand Prix",
    "paul_ricard": "French Grand Prix",
    "budapest": "Hungarian Grand Prix",
    "hungaroring": "Hungarian Grand Prix",
    "spa": "Belgian Grand Prix",
    "spa-francorchamps": "Belgian Grand Prix",
    "zandvoort": "Dutch Grand Prix",
    "monza": "Italian Grand Prix",
    "marina_bay": "Singapore Grand Prix",
    "singapore": "Singapore Grand Prix",
    "suzuka": "Japanese Grand Prix",
    "lusail": "Qatar Grand Prix",
    "austin": "United States Grand Prix",
    "americas": "United States Grand Prix",
    "mexico_city": "Mexico City Grand Prix",
    "rodriguez": "Mexico City Grand Prix",
    "são_paulo": "São Paulo Grand Prix",
    "interlagos": "São Paulo Grand Prix",
    "las_vegas": "Las Vegas Grand Prix",
    "vegas": "Las Vegas Grand Prix",
    "yas_island": "Abu Dhabi Grand Prix",
    "yas_marina": "Abu Dhabi Grand Prix",
    "portimão": "Portuguese Grand Prix",
    "portimao": "Portuguese Grand Prix",
    "mugello": "Tuscan Grand Prix",
    "nürburgring": "Eifel Grand Prix",
    "nurburgring": "Eifel Grand Prix",
    "istanbul": "Turkish Grand Prix",
    "sochi": "Russian Grand Prix",
    "shanghai": "Chinese Grand Prix",
    "hockenheim": "German Grand Prix",
    "hockenheimring": "German Grand Prix",
    "bahrain_outer": "Bahrain Outer",
}
